### ISSUE TITLE
Button hover color not darker

### ISSUE THREAD

**Issue by dawnerd** [firstandthird/clientkit#111]
Might be an issue with how darkness(20%) works.

![image](https://cloud.githubusercontent.com/assets/24781/18263804/5e5cdea8-73c1-11e6-8f8a-ff69966e4fef.png)

`button-primary-bg:` is set to `rgba(204, 136, 58, 1)`

Perhaps we change it from assuming it's always 20% darker and just having a config for `button-primary-hover-bg`

**Comment by jgallen23** [comment]
yeah, I'm cool with that

**Comment by chrisopedia** [comment]
How are you using `darkness()`?  The button mixin is already unweildy with the 6 arguments currently, so I think it'd be better if we could figure out that or use a different color plugin.

**Comment by jgallen23** [comment]
hover color is already a passed in param

**Comment by chrisopedia** [comment]
Ah yeah, well lets get rid of that as an argument then and figure out the `darkness()`
